# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_Chess' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS_Chess
 pod 'Firebase/Core'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'

  target 'IOS_ChessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS_ChessUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
